### ISSUE TITLE
Todo.md Relevancy

### ISSUE THREAD

**Issue by suhailskhan** [oalejel/Athan-Utility#10]
From [Athan Utility/Todo.md](https://github.com/oalejel/Athan-Utility/blob/47eceb55c9b4841929e91b3c39b18f78bfd982cb/Athan%20Utility/Todo.md), how much of it is still relevant? Should answer to this wait until next push, perhaps?

**Comment by oalejel** [comment]
Salam Suhail, I have working changes that will be pushed once my update with StandBy mode and other features are ready for iOS 17.

When it comes to ideas, please submit a suggestion before working on a PR, as I’m very particular about the design and function of this App, and have limited time to review and merge PRs. I appreciate thoughtful feedback and discussion, but this project is not meant as a matter of daily discussion. The primary purpose of this Repo is transparency. I am not a student and don’t have the free time to have regular discussion on small details of files that don’t affect the correctness of the app. I appreciate your enthusiasm, but please practice patience.

**Comment by suhailskhan** [comment]
Walaikum assalam. My apologies for any over-inquiring I have done, and I completely understand. Please do understand that my frequency of discussion over the project is only temporary and was not intended to last. It will be more tempered going forward inn shaa Allah.

To be clear, I already had in mind my own ideas for improvements to the app, but I was curious about the things listed in the Todo file as it seemed like another good place to start for improvements and/or issues to resolve. Although I realize now I could evaluate them for myself and decide if it is worth working on.

I do acknowledge that this inquiry was not essential by any means, and will avoid these in the future.

**Comment by suhailskhan** [comment]
> When it comes to ideas, please submit a suggestion before working on a PR, as I’m very particular about the design and function of this App, and have limited time to review and merge PRs.

If you don’t mind I can bring my suggestions now and open them as issues if that is okay with you. In brief, a few top ones I had in mind was moving from using SiriKit Intents to App Intents for iOS 16/watchOS 9 and above, using TipKit to bring attention to features like the calendar view, and an overhaul to the Watch app with a watchOS 10-like UI style and that removes WatchKit dependency. Another is getting a widget for the new Smart Stack in watchOS 10, but I suspect this one is already on your agenda.

Regardless, Jazak Allahu khairan for your graceful responses despite my, at times, overly frequent inquiries.
