### ISSUE TITLE
Times on Apple Watch are wrong

### ISSUE THREAD

**Issue by mactabish** [oalejel/Athan-Utility#5]
After setting location on the iPhone app, the times on the Apple Watch are completely different. The location on the Apple Watch shows up correctly.

**Comment by oalejel** [comment]
Salam! I noticed that older versions of watchOS had issues with communicating updates with a companion app, but I'll Inshallah I'll look into this once I complete my internship and finally have the freedom to make changes to the App. Sorry for the delay! Ramadan Mubarak!
