### ISSUE TITLE
Repository does not appear to reflect most recent build on App Store

### ISSUE THREAD

**Issue by suhailskhan** [oalejel/Athan-Utility#7]
I noticed that version 6.2 of the app was published to the App Store this September, however the last push to the repository is from 2021. Are there plans to publish new commits to the repo?

**Comment by zenginerler** [comment]
Hi @oalejel 👋, I wanted to ask the same question. Seems like you don't use this repository as the main code base anymore. I **really** like this app and I wanted to work on a tvOS version (for Apple TV). Do you have any plans to accept contributions?

**Comment by suhailskhan** [comment]
It has been close to a year since opening the issue, and months since I sent a message regarding this to the app’s feedback email. I have now left an App Store review talking about this.

**Comment by suhailskhan** [comment]
Omar, of course, does not owe us the up-to-date code committed this repo, but it would be nice to get word from him on the future of the public repository as well as things like accepting contributions. Most crucially, the app is proclaimed to be open-source, yet the public source code is for a release that is 2+ years out of date.

**Comment by oalejel** [comment]
Salam Suhail! Sorry I’ve had a few things on my plate and didn’t get a chance to see this. I’d love to start building on this app with open source contributions inshallah. Please share any suggestions and PRs! JAK

**Comment by oalejel** [comment]
There may be a local update to the app that hasn’t been pushed to remote. Will be pushing tomorrow iA

**Comment by suhailskhan** [comment]
> Salam Suhail! Sorry I’ve had a few things on my plate and didn’t get a chance to see this.

Walaikum assalam, no worries, really glad to hear from you!

> I’d love to start building on this app with open source contributions inshallah.

Inn shaa Allah.

> Please share any suggestions and PRs! JAK

Will do.

**Comment by suhailskhan** [comment]
> There may be a local update to the app that hasn’t been pushed to remote. Will be pushing tomorrow iA

This would be really good news. Much appreciated!

**Comment by suhailskhan** [comment]
@oalejel Any update for pushing today?

**Comment by oalejel** [comment]
In the next hour iA. I have work on the pacific coast.Omar Al-EjelOn Sep 21, 2023, at 6:52 PM, Suhail Khan ***@***.***> wrote:﻿
@oalejel Any update for pushing today?

**Comment by oalejel** [comment]
Update: there are some working changes that need a cleanup before being pushed. I'm pretty busy this week but iA will post an update when I push. In the meantime, if you have an idea for a PR, feel free to start a discussion so we can align on a potential PR merge.
